languageCode = "en-us"
title = "Portofolio"
baseURL = "https://chocopie116.me/"

[params]
    title = "Tsubasa by HTML5 UP"
    major = "Hi, my name is Tsubasa"
    coverimageurl = "images/cover.jpg"
    subtitle = "A responsive site template designed by HTML5 UP"
    subtitleline2 = "and released under the Creative Commons."
    bannerCTA = "Get Started"
    copyrightText = "Untitled"
    googleAnalyticsId = "XXXXXXXX-X"

[params.author]
  firstname = "Tsubasa"
  lastname = "by HTML5 UP"

[params.textsection]
  title = "Massa libero"
  description = "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. Mauris aliquet magna magna sed nunc rhoncus pharetra. Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero. Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."
  linkurl = "http://www.google.com"
  linktext = "Get Started"

[params.contact]
  formposturl = ""


[params.social]
  twitter = "chocopie116"
  facebook = "chocopie116"
  instagram = "chocopie116"
  github = "chocopie116"
  linkedin = "linkedin"


[taxonomies]
  category = "categories"
