# Site settings
baseURL = "https://chocopie116.me/"
languageCode = "en-us"
title = "Portofolio"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-121866338-2"


# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # 404 error customization
  [params.error404]
    heading = ""
    text = "Please visit [this page](/)"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Aliquam"
      subtitle = "Ipsum Dolor Sit Amet"
      image = "pic01.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "Tempus"
      subtitle = "Feugiat Amet Tempus"
      image = "pic02.jpg"
      url = "blogs/tempus"

    [[params.tiles.showcase]]
      title = "Magna"
      subtitle = "Lorem Etiam Nullam"
      image = "pic03.jpg"
      url = "blogs/magna"

    [[params.tiles.showcase]]
      title = "Ipsum"
      subtitle = "Nisl Sed Aliquam"
      image = "pic04.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Consequat"
      subtitle = "Ipsum Dolor Sit Amet"
      image = "pic05.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Etiam"
      subtitle = "Feugiat Amet Tempus"
      image = "pic06.jpg"
      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

