# Site settings
baseURL = "https://chocopie116.me/"
languageCode = "en-us"
title = "Tsubasa KAJINUMA"
theme = "forty"
googleAnalytics = "UA-121866338-2"


[permalinks]
projects = "/projects/:filename/"

